In this notebook, I will explore the relation between the song lyrics and the tweets.

Connect drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Open the data

In [3]:
# data with the songs
main_df = pd.read_csv('/content/drive/MyDrive/Thesis docs/User-Songs-Music-Group.xls')

In [13]:
main_df

,Unnamed: 0,created_at,music_source,title,artist,disorder,sentiment_direction,sentiment_score,music_url,lyric,emotion_anger_score,emotion_disgust_score,emotion_fear_score,emotion_joy_score,emotion_neutral_score,emotion_sadness_score,emotion_surprise_score,anonymized_author_id,anonymized_tweet_id
0,0,2021-06-25 01:18:42-04:00,spotify,Burnin Bridges / Long Day (feat. IDK),Quadeca,depression,POSITIVE,0.9971,https://open.spotify.com/track/0B5mjEPetRaVGBs...,Highest To Lowest: Quadeca LyricsQuadeca's Son...,0.0294,0.0014,0.0132,0.2346,0.0993,0.0832,0.5390,0ef1ff6f271d5cb3541f6995,e611b266fd0d9de7dd2696d2
1,1,2021-09-25 12:05:15-04:00,spotify,She's A Lady,Tom Jones,control,POSITIVE,0.9988,https://open.spotify.com/track/5QfQ5iROTerk3MZ...,She’s a Lady Lyrics[Verse 1]\nWell she's all y...,0.0271,0.0203,0.0071,0.1162,0.1262,0.0335,0.6696,12b35a1f4485cf4aff1a634a,c04e17b275379c024e6179a4
2,2,2022-05-14 16:57:16-04:00,spotify,Lilies of the Valley,David Byrne,control,POSITIVE,0.9532,https://open.spotify.com/track/5mwlD1lkAGHrd2l...,Lilies of the Valley Lyrics[Verse 1]\nMomma sh...,0.0252,0.0054,0.0556,0.5990,0.0678,0.2116,0.0354,12b35a1f4485cf4aff1a634a,a6b49eeb6e211e7940be6593
3,3,2021-05-24 10:04:29-04:00,spotify,School's Out,Alice Cooper,control,NEGATIVE,0.9995,https://open.spotify.com/track/5Z8EDau8uNcP1E8...,"School’s Out Lyrics[Verse 1]\nWell, we got no ...",0.1258,0.1330,0.0149,0.0306,0.1615,0.5014,0.0330,12b35a1f4485cf4aff1a634a,bc836b7694e9c922f374ee74
4,4,2022-01-09 15:12:28-05:00,spotify,Call My Friends,Shawn Mendes,depression,POSITIVE,0.9978,https://open.spotify.com/track/6KVxMOxlSYpC5nr...,"Call My Friends Lyrics[Verse 1]\nRight now, I'...",0.0016,0.0006,0.0015,0.0075,0.0055,0.9777,0.0057,3e06169cafdc66d26a9b9ebb,7970bb8c13ff94ee62102db0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78408,78408,2020-09-08 05:01:37-04:00,spotify,Sincerity Is Scary,The 1975,control,NEGATIVE,0.9992,https://open.spotify.com/track/6HguG9HRb1Ke1bh...,Sincerity Is Scary Lyrics[Verse 1]\nIrony is o...,0.8493,0.0488,0.0085,0.0034,0.0163,0.0450,0.0288,0a565f604873557ab8531953,604cb74f6f2b528dc783ce19
78409,78409,2020-08-14 04:47:01-04:00,spotify,BBIBBI,IU,control,NEGATIVE,0.9905,https://open.spotify.com/track/4as4XEOR03oGm1S...,IU - BBIBBI (English Translation) Lyrics[Verse...,0.1678,0.0083,0.0646,0.0146,0.0556,0.0404,0.6488,0a565f604873557ab8531953,d4d3dea422795defe088c9a6
78410,78410,2022-05-08 12:54:01-04:00,apple,7 Things,Miley Cyrus,control,NEGATIVE,0.9848,https://music.apple.com/us/album/7-things/1440...,"7 Things Lyrics[Intro]\n(Sha, sha, sha)\n\n[Ve...",0.0914,0.0246,0.3393,0.0870,0.0451,0.3945,0.0181,9964394c7207f82479ff2a6c,2b9f89a573a5f9aadd4b1f59
78411,78411,2021-10-15 18:40:26-04:00,apple,Mexican Radio,SPM,control,NEGATIVE,0.9800,https://music.apple.com/us/album/mexican-radio...,Mexican Radio Lyrics[Intro](Spoken)\nOne-doubl...,0.1279,0.0051,0.0146,0.1729,0.2288,0.2386,0.2120,17df8fc9f5a8a3f490ad478a,bba2027e3152da9d03f70bfa
78412,78412,2021-10-11 17:06:14-04:00,apple,American Girl,Bonnie McKee,control,POSITIVE,0.9983,https://music.apple.com/us/album/american-girl...,American Girl Lyrics[Verse 1]\nI fell in love ...,0.0336,0.0064,0.0232,0.2788,0.4191,0.1409,0.0980,17df8fc9f5a8a3f490ad478a,e973becd755977549476704a

In [5]:
# data with the tweets
tweets_df = pd.read_csv('/content/drive/MyDrive/Thesis docs/User-Profiles-Music-Group.xls')

In [6]:
tweets_df.head()

,Unnamed: 0,location,created_at,verified,description,disorder,followers_count,following_count,listed_count,tweet_count,anonymized_id
0,0,NaN,2012-06-18 20:40:19-04:00,False,step into the daylight & let it go. just a fan...,ptsd,3817.0,1481.0,43.0,131271.0,386e39f1f8fdc28232027934
1,1,Canada,2012-08-06 01:21:06-04:00,False,"Hi, I’m human and it hurts. #JusticeForJohnnyD...",depression,14097.0,7789.0,23.0,111366.0,658282d97cb670357d820173
2,2,she/her,2019-04-05 17:26:06-04:00,False,your local 90s emo kid that went to art school 🎨✨,depression,128.0,388.0,1.0,6456.0,4d1b7e96f71da3d6a4fe1d90
3,3,"Virginia, USA",2018-03-07 11:51:56-05:00,False,••✨🥔😈I AM THE POTATO DADDY😈🥔✨•• 🔆Awkward & Fli...,bipolar,13064.0,9632.0,19.0,27996.0,28e76687ffe685b7295651d1
4,4,deez nuts,2020-09-03 20:13:56-04:00,False,#YOONGI & #SOOBIN’s professional hand holder ₊...,anxiety,107.0,122.0,1.0,11445.0,39da522a9f55bf4864679941

Combine IDs to the songs

In [7]:
# unique IDs 
song_ids = set(main_df['anonymized_author_id'])
tweets_ids = set(tweets_df['anonymized_id'])

common_ids = song_ids.intersection(tweets_ids)

print(f"Number of unique song IDs: {len(song_ids)}")
print(f"Number of unique tweet IDs: {len(tweets_ids)}")
print(f"Number of common IDs: {len(common_ids)}")

Number of unique song IDs: 5767
Number of unique tweet IDs: 5767
Number of common IDs: 5767

In [8]:
main_df_merged = main_df.merge(
    tweets_df[['anonymized_id', 'description']],
    left_on='anonymized_author_id',
    right_on='anonymized_id',
    how='left'
)

In [9]:
main_df_merged

,Unnamed: 0,created_at,music_source,title,artist,disorder,sentiment_direction,sentiment_score,music_url,lyric,...,emotion_disgust_score,emotion_fear_score,emotion_joy_score,emotion_neutral_score,emotion_sadness_score,emotion_surprise_score,anonymized_author_id,anonymized_tweet_id,anonymized_id,description
0,0,2021-06-25 01:18:42-04:00,spotify,Burnin Bridges / Long Day (feat. IDK),Quadeca,depression,POSITIVE,0.9971,https://open.spotify.com/track/0B5mjEPetRaVGBs...,Highest To Lowest: Quadeca LyricsQuadeca's Son...,...,0.0014,0.0132,0.2346,0.0993,0.0832,0.5390,0ef1ff6f271d5cb3541f6995,e611b266fd0d9de7dd2696d2,0ef1ff6f271d5cb3541f6995,"18. He/They. Bisexual. Socialist. Filmmaker, m..."
1,1,2021-09-25 12:05:15-04:00,spotify,She's A Lady,Tom Jones,control,POSITIVE,0.9988,https://open.spotify.com/track/5QfQ5iROTerk3MZ...,She’s a Lady Lyrics[Verse 1]\nWell she's all y...,...,0.0203,0.0071,0.1162,0.1262,0.0335,0.6696,12b35a1f4485cf4aff1a634a,c04e17b275379c024e6179a4,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
2,2,2022-05-14 16:57:16-04:00,spotify,Lilies of the Valley,David Byrne,control,POSITIVE,0.9532,https://open.spotify.com/track/5mwlD1lkAGHrd2l...,Lilies of the Valley Lyrics[Verse 1]\nMomma sh...,...,0.0054,0.0556,0.5990,0.0678,0.2116,0.0354,12b35a1f4485cf4aff1a634a,a6b49eeb6e211e7940be6593,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
3,3,2021-05-24 10:04:29-04:00,spotify,School's Out,Alice Cooper,control,NEGATIVE,0.9995,https://open.spotify.com/track/5Z8EDau8uNcP1E8...,"School’s Out Lyrics[Verse 1]\nWell, we got no ...",...,0.1330,0.0149,0.0306,0.1615,0.5014,0.0330,12b35a1f4485cf4aff1a634a,bc836b7694e9c922f374ee74,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
4,4,2022-01-09 15:12:28-05:00,spotify,Call My Friends,Shawn Mendes,depression,POSITIVE,0.9978,https://open.spotify.com/track/6KVxMOxlSYpC5nr...,"Call My Friends Lyrics[Verse 1]\nRight now, I'...",...,0.0006,0.0015,0.0075,0.0055,0.9777,0.0057,3e06169cafdc66d26a9b9ebb,7970bb8c13ff94ee62102db0,3e06169cafdc66d26a9b9ebb,ariana & shawn + tom | he/him | 19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78408,78408,2020-09-08 05:01:37-04:00,spotify,Sincerity Is Scary,The 1975,control,NEGATIVE,0.9992,https://open.spotify.com/track/6HguG9HRb1Ke1bh...,Sincerity Is Scary Lyrics[Verse 1]\nIrony is o...,...,0.0488,0.0085,0.0034,0.0163,0.0450,0.0288,0a565f604873557ab8531953,604cb74f6f2b528dc783ce19,0a565f604873557ab8531953,// i t s n o t l i v i n g i f i t s n o t w i...
78409,78409,2020-08-14 04:47:01-04:00,spotify,BBIBBI,IU,control,NEGATIVE,0.9905,https://open.spotify.com/track/4as4XEOR03oGm1S...,IU - BBIBBI (English Translation) Lyrics[Verse...,...,0.0083,0.0646,0.0146,0.0556,0.0404,0.6488,0a565f604873557ab8531953,d4d3dea422795defe088c9a6,0a565f604873557ab8531953,// i t s n o t l i v i n g i f i t s n o t w i...
78410,78410,2022-05-08 12:54:01-04:00,apple,7 Things,Miley Cyrus,control,NEGATIVE,0.9848,https://music.apple.com/us/album/7-things/1440...,"7 Things Lyrics[Intro]\n(Sha, sha, sha)\n\n[Ve...",...,0.0246,0.3393,0.0870,0.0451,0.3945,0.0181,9964394c7207f82479ff2a6c,2b9f89a573a5f9aadd4b1f59,9964394c7207f82479ff2a6c,“oh why’d you have to be so cute”♡ imagine🤍19 ...
78411,78411,2021-10-15 18:40:26-04:00,apple,Mexican Radio,SPM,control,NEGATIVE,0.9800,https://music.apple.com/us/album/mexican-radio...,Mexican Radio Lyrics[Intro](Spoken)\nOne-doubl...,...,0.0051,0.0146,0.1729,0.2288,0.2386,0.2120,17df8fc9f5a8a3f490ad478a,bba2027e3152da9d03f70bfa,17df8fc9f5a8a3f490ad478a,do it #doggystyle / i love my girlfriend maría...
78412,78412,2021-10-11 17:06:14-04:00,apple,American Girl,Bonnie McKee,control,POSITIVE,0.9983,https://music.apple.com/us/album/american-girl...,American Girl Lyrics[Verse 1]\nI fell in love ...,...,0.0064,0.0232,0.2788,0.4191,0.1409,0.0980,17df8fc9f5a8a3f490ad478a,e973becd755977549476704a,17df8fc9f5a8a3f490ad478a,do it #doggystyle / i love my girlfriend maría...

In [10]:
main_df_merged = main_df_merged.drop(columns=["created_at", "music_source", "music_url", "anonymized_tweet_id"])

main_df_merged.head()

,Unnamed: 0,title,artist,disorder,sentiment_direction,sentiment_score,lyric,emotion_anger_score,emotion_disgust_score,emotion_fear_score,emotion_joy_score,emotion_neutral_score,emotion_sadness_score,emotion_surprise_score,anonymized_author_id,anonymized_id,description
0,0,Burnin Bridges / Long Day (feat. IDK),Quadeca,depression,POSITIVE,0.9971,Highest To Lowest: Quadeca LyricsQuadeca's Son...,0.0294,0.0014,0.0132,0.2346,0.0993,0.0832,0.5390,0ef1ff6f271d5cb3541f6995,0ef1ff6f271d5cb3541f6995,"18. He/They. Bisexual. Socialist. Filmmaker, m..."
1,1,She's A Lady,Tom Jones,control,POSITIVE,0.9988,She’s a Lady Lyrics[Verse 1]\nWell she's all y...,0.0271,0.0203,0.0071,0.1162,0.1262,0.0335,0.6696,12b35a1f4485cf4aff1a634a,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
2,2,Lilies of the Valley,David Byrne,control,POSITIVE,0.9532,Lilies of the Valley Lyrics[Verse 1]\nMomma sh...,0.0252,0.0054,0.0556,0.5990,0.0678,0.2116,0.0354,12b35a1f4485cf4aff1a634a,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
3,3,School's Out,Alice Cooper,control,NEGATIVE,0.9995,"School’s Out Lyrics[Verse 1]\nWell, we got no ...",0.1258,0.1330,0.0149,0.0306,0.1615,0.5014,0.0330,12b35a1f4485cf4aff1a634a,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
4,4,Call My Friends,Shawn Mendes,depression,POSITIVE,0.9978,"Call My Friends Lyrics[Verse 1]\nRight now, I'...",0.0016,0.0006,0.0015,0.0075,0.0055,0.9777,0.0057,3e06169cafdc66d26a9b9ebb,3e06169cafdc66d26a9b9ebb,ariana & shawn + tom | he/him | 19

In [12]:
main_df_merged = main_df_merged[main_df_merged["disorder"].isin(["depression", "control"])]

main_df_merged

,Unnamed: 0,title,artist,disorder,sentiment_direction,sentiment_score,lyric,emotion_anger_score,emotion_disgust_score,emotion_fear_score,emotion_joy_score,emotion_neutral_score,emotion_sadness_score,emotion_surprise_score,anonymized_author_id,anonymized_id,description
0,0,Burnin Bridges / Long Day (feat. IDK),Quadeca,depression,POSITIVE,0.9971,Highest To Lowest: Quadeca LyricsQuadeca's Son...,0.0294,0.0014,0.0132,0.2346,0.0993,0.0832,0.5390,0ef1ff6f271d5cb3541f6995,0ef1ff6f271d5cb3541f6995,"18. He/They. Bisexual. Socialist. Filmmaker, m..."
1,1,She's A Lady,Tom Jones,control,POSITIVE,0.9988,She’s a Lady Lyrics[Verse 1]\nWell she's all y...,0.0271,0.0203,0.0071,0.1162,0.1262,0.0335,0.6696,12b35a1f4485cf4aff1a634a,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
2,2,Lilies of the Valley,David Byrne,control,POSITIVE,0.9532,Lilies of the Valley Lyrics[Verse 1]\nMomma sh...,0.0252,0.0054,0.0556,0.5990,0.0678,0.2116,0.0354,12b35a1f4485cf4aff1a634a,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
3,3,School's Out,Alice Cooper,control,NEGATIVE,0.9995,"School’s Out Lyrics[Verse 1]\nWell, we got no ...",0.1258,0.1330,0.0149,0.0306,0.1615,0.5014,0.0330,12b35a1f4485cf4aff1a634a,12b35a1f4485cf4aff1a634a,One song everyday (hopefully) of 2020.
4,4,Call My Friends,Shawn Mendes,depression,POSITIVE,0.9978,"Call My Friends Lyrics[Verse 1]\nRight now, I'...",0.0016,0.0006,0.0015,0.0075,0.0055,0.9777,0.0057,3e06169cafdc66d26a9b9ebb,3e06169cafdc66d26a9b9ebb,ariana & shawn + tom | he/him | 19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78408,78408,Sincerity Is Scary,The 1975,control,NEGATIVE,0.9992,Sincerity Is Scary Lyrics[Verse 1]\nIrony is o...,0.8493,0.0488,0.0085,0.0034,0.0163,0.0450,0.0288,0a565f604873557ab8531953,0a565f604873557ab8531953,// i t s n o t l i v i n g i f i t s n o t w i...
78409,78409,BBIBBI,IU,control,NEGATIVE,0.9905,IU - BBIBBI (English Translation) Lyrics[Verse...,0.1678,0.0083,0.0646,0.0146,0.0556,0.0404,0.6488,0a565f604873557ab8531953,0a565f604873557ab8531953,// i t s n o t l i v i n g i f i t s n o t w i...
78410,78410,7 Things,Miley Cyrus,control,NEGATIVE,0.9848,"7 Things Lyrics[Intro]\n(Sha, sha, sha)\n\n[Ve...",0.0914,0.0246,0.3393,0.0870,0.0451,0.3945,0.0181,9964394c7207f82479ff2a6c,9964394c7207f82479ff2a6c,“oh why’d you have to be so cute”♡ imagine🤍19 ...
78411,78411,Mexican Radio,SPM,control,NEGATIVE,0.9800,Mexican Radio Lyrics[Intro](Spoken)\nOne-doubl...,0.1279,0.0051,0.0146,0.1729,0.2288,0.2386,0.2120,17df8fc9f5a8a3f490ad478a,17df8fc9f5a8a3f490ad478a,do it #doggystyle / i love my girlfriend maría...
78412,78412,American Girl,Bonnie McKee,control,POSITIVE,0.9983,American Girl Lyrics[Verse 1]\nI fell in love ...,0.0336,0.0064,0.0232,0.2788,0.4191,0.1409,0.0980,17df8fc9f5a8a3f490ad478a,17df8fc9f5a8a3f490ad478a,do it #doggystyle / i love my girlfriend maría...

Get the data frame with the VAs

In [15]:
VA_df = pd.read_csv("/content/drive/MyDrive/Thesis docs/sentiment_song_level_wide_enriched.csv")

VA_df.head()

,artist,title,mean_arousal_VAD,mean_dominance_VAD,mean_valence_VAD
0,"""Weird Al"" Yankovic",Fat,0.173124,0.100035,-0.033980
1,#Freekd,ACTUALLY,0.242156,0.115553,-0.073895
2,#Freekd,JUMPOFF,0.159050,0.082422,0.011588
3,$NOT,Moon & Stars (feat. Maggie Lindemann),0.107910,0.069382,0.054230
4,$UICIDEBOY$,FUCKTHEPOPULATION,0.253423,0.128955,-0.305391